name: Action Test

on: 
  issues:
    types: 
      - opened

jobs:
  label:
    
    runs-on: ubuntu-latest
    name: Add label to Issue if it is secure
    steps:
      - uses: actions/checkout@v3
      - uses: ./ # load and run local action
        name: Label an issue
        with:
          rqcode-token: ${{ secrets.RQCODE_TOKEN }}
          platform: google_android_10.x
          # username: ${{ secrets.ARQAN_USER }}
          # password: ${{ secrets.ARQAN_PASS }}
          create-issues: 'false'
